# Generated by Django 5.2.9 on 2026-01-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_alter_accesslog_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='card_id',
            field=models.CharField(max_length=100),
        ),
    ]
